version: '3'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Map container port 80 to host port 5000
    #volumes:
    #  - /home/tousif/web:./  # Mount the application code
    environment:
      - PORT=80  # Set the environment variable for Flask to run on port 80
#
#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"  # Map container port 80 to host port 80
#    volumes:
#      - /home/tousif/web/nginx.conf:/etc/nginx/nginx.conf  # Mount Nginx configuration file
#    depends_on:
#      - flask-app  # Ensure Flask app is running before Nginx starts
